using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using UnityGameTranslator.Installer.Core.Api;
using UnityGameTranslator.Installer.Core.Catalog;
using UnityGameTranslator.Installer.Core.Detection;
using UnityGameTranslator.Installer.Core.Install;
using UnityGameTranslator.Installer.Core.Model;
using UnityGameTranslator.Installer.Core.Platform;
using UnityGameTranslator.Installer.Core.Settings;

namespace UnityGameTranslator.Installer.Gui;

/// <summary>
/// The window. It renders what Core decided and calls back into Core — it holds no rule of its
/// own, which is why the command line and this show the same thing.
/// </summary>
public partial class MainWindow : Window
{
    private readonly IPlatform _platform;
    private LoaderCatalogDocument _catalog = null!;
    private GameInventory _inventory = null!;

    private readonly List<GameInstall> _games = new();
    private GameInstall? _selected;

    private SettingsStore _settings = null!;
    private OnlineCatalogCache _online = null!;
    private CancellationTokenSource? _sweep;

    /// <summary>Situation per game path, so a row can be redrawn without redoing the work.</summary>
    private readonly Dictionary<string, GameSituationInfo> _situations =
        new(StringComparer.OrdinalIgnoreCase);

    private Situation? _filter;

    public MainWindow()
    {
        // InitializeComponent is generated by the Avalonia XAML compiler, and it is what wires
        // up the x:Name fields. Declaring one by hand hides it, leaving every named control
        // null — which fails at construction, not at build.
        InitializeComponent();

        _platform = PlatformFactory.Create();

        SearchBox.TextChanged += (_, _) => RefreshList();
        RescanButton.Click += async (_, _) => await ScanAsync();
        AddFolderButton.Click += async (_, _) => await AddFolderAsync();
        FoldersButton.Click += async (_, _) => await ManageFoldersAsync();
        AboutButton.Click += async (_, _) => await new AboutWindow().ShowDialog(this);
        GameList.SelectionChanged += async (_, _) => await ShowSelectedAsync();

        _settings = new SettingsStore(_platform);
        _online = new OnlineCatalogCache(_platform);

        BuildLanguageBox();
        BuildFilterBar();

        Loaded += async (_, _) => await ScanAsync();
    }

    // ---------------------------------------------------------------- scanning

    private async Task ScanAsync()
    {
        Busy(true, "Looking for the loader catalog...");

        _sweep?.Cancel();

        var result = await Task.Run(() => new CatalogProvider(_platform).Get());
        _catalog = result.Document;
        _inventory = new GameInventory(_platform, _catalog, new CatalogApiClient());

        Status($"Catalog: {_catalog.Loaders.Count} loaders ({result.Source}). Scanning your drives...");

        var found = await Task.Run(() => _inventory.ScanAll());

        _games.Clear();
        _games.AddRange(found.OrderBy(g => g.Name, StringComparer.OrdinalIgnoreCase));

        var blocked = _games.Count(g => !g.IsModdable);
        SubtitleText.Text = blocked == 0
            ? $"{_games.Count} Unity games found"
            : $"{_games.Count} Unity games found, {blocked} that cannot be modded";

        RecomputeSituations();
        RefreshList();
        Busy(false, "Ready.");

        StartOnlineSweep();
    }

    /// <summary>
    /// Fills in what the community has, in the background.
    ///
    /// The window is usable immediately and rows sharpen as answers arrive, rather than the list
    /// staying empty until every game has been looked up. Only Steam gives us an id to look up
    /// with, so the others simply say so instead of pretending to know.
    /// </summary>
    private void StartOnlineSweep()
    {
        if (!_settings.Current.OnlineMode) return;

        var ids = _games.Where(g => g.IsModdable && g.SteamAppId is not null)
                        .Select(g => g.SteamAppId!)
                        .ToList();
        if (ids.Count == 0) return;

        _sweep = new CancellationTokenSource();
        var token = _sweep.Token;

        _ = Task.Run(async () =>
        {
            var done = 0;
            await _online.RefreshAsync(ids, async (appId, _) =>
            {
                done++;
                var progress = done;
                await Dispatcher.UIThread.InvokeAsync(() =>
                {
                    RecomputeSituations();
                    RefreshList();
                    Status($"Checking community translations... {progress}/{ids.Count}");
                });
            }, token);

            if (!token.IsCancellationRequested)
                await Dispatcher.UIThread.InvokeAsync(() => Status("Ready."));
        }, token);
    }

    /// <summary>
    /// Rebuilds every row's situation from what is currently known. Cheap: it reads the caches,
    /// it does not go looking again.
    /// </summary>
    private void RecomputeSituations()
    {
        var language = _settings.ResolveTargetLanguage();
        _situations.Clear();

        foreach (var game in _games)
        {
            var online = _online.Peek(game.SteamAppId);
            var report = new GameReport { Game = game };

            var descriptor = _catalog.Loaders.FirstOrDefault(
                l => l.Id == LoaderProbe.Detect(game.Path, _catalog)?.Id);

            if (descriptor is not null)
            {
                report.InstalledPluginVersion =
                    LocalTranslationProbe.ReadInstalledPluginVersion(game.Path, descriptor);
                report.LocalTranslation = LocalTranslationProbe.Read(game.Path, descriptor);
            }

            if (online is not null)
            {
                report.OnlineTranslations = online;
                if (report.LocalTranslation?.Uuid is { Length: > 0 } uuid)
                {
                    report.MatchingOnline = online.FirstOrDefault(
                        t => string.Equals(t.Uuid, uuid, StringComparison.OrdinalIgnoreCase));
                }
            }

            var checkedOnline = online is not null
                                || game.SteamAppId is null
                                || !_settings.Current.OnlineMode;

            _situations[game.Path] = SituationReader.Read(report, language, checkedOnline);
        }
    }

    // ---------------------------------------------------------------- language and filters

    private void BuildLanguageBox()
    {
        // "auto" first: following the system is a legitimate answer, and it is the mod's default.
        LanguageBox.Items.Add(new ComboBoxItem { Content = "System language", Tag = "auto" });
        foreach (var (code, name) in Languages.All())
            LanguageBox.Items.Add(new ComboBoxItem { Content = name, Tag = code });

        var current = _settings.Current.TargetLanguage;
        foreach (var item in LanguageBox.Items.OfType<ComboBoxItem>())
        {
            if (string.Equals(item.Tag as string, current, StringComparison.OrdinalIgnoreCase))
            {
                LanguageBox.SelectedItem = item;
                break;
            }
        }
        LanguageBox.SelectedItem ??= LanguageBox.Items.OfType<ComboBoxItem>().FirstOrDefault();

        LanguageBox.SelectionChanged += (_, _) =>
        {
            if (LanguageBox.SelectedItem is not ComboBoxItem { Tag: string code }) return;
            if (code == _settings.Current.TargetLanguage) return;

            var updated = _settings.Current;
            updated.TargetLanguage = code;
            updated.Reviewed = true;
            _settings.Save(updated);

            // The language is the context for every row: changing it re-reads the whole list.
            RecomputeSituations();
            RefreshList();
        };
    }

    private void BuildFilterBar()
    {
        (string Label, Situation? Value)[] filters =
        {
            ("All", null),
            ("Playable in my language", Situation.TranslationAvailable),
            ("Needs a translator", Situation.NotTranslatedYet),
            ("Already set up", Situation.Ready),
            ("Cannot be modded", Situation.Blocked),
        };

        foreach (var (label, value) in filters)
        {
            var button = new Button
            {
                Content = label,
                FontSize = 11,
                Tag = value,
                Margin = new Avalonia.Thickness(0, 0, 6, 6),
            };
            button.Click += (_, _) =>
            {
                _filter = value;
                foreach (var other in FilterBar.Children.OfType<Button>())
                    other.Classes.Set("primary", ReferenceEquals(other, button));
                RefreshList();
            };
            FilterBar.Children.Add(button);
        }

        (FilterBar.Children.FirstOrDefault() as Button)?.Classes.Add("primary");
    }

    private async Task AddFolderAsync()
    {
        var folders = await StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions
        {
            Title = "Where is the game installed?",
            AllowMultiple = false,
        });

        var path = folders.FirstOrDefault()?.TryGetLocalPath();
        if (path is null) return;

        // Remember it, so the next run finds it without asking again — and so it can be shown
        // and taken back out. A folder added and then invisible is a folder the user cannot
        // manage.
        _inventory.Folders.Add(path);

        // The folder may hold one game or a whole library; scanning covers both.
        var found = StoreScanner
            .ScanFolder(Path.GetFullPath(path), GameStore.Manual, maxDepth: 2)
            .ToList();

        if (found.Count == 0)
        {
            Status($"No Unity game found in {path}. The folder was still added to your list.");
            RefreshList();
            return;
        }

        var added = 0;
        foreach (var game in found)
        {
            if (_games.Any(g => string.Equals(g.Path, game.Path, StringComparison.OrdinalIgnoreCase)))
                continue;
            _games.Add(game);
            added++;
        }

        _games.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));

        Status(added == 0
            ? "Those games were already listed."
            : $"Added {added} game(s) from {path}.");

        RefreshList();
        SelectByPath(found[0].Path);
    }

    /// <summary>
    /// Shows the folders the user added, and lets them be removed. Adding a folder with no way
    /// to see or undo it is a one-way door.
    /// </summary>
    private async Task ManageFoldersAsync()
    {
        var folders = _inventory.Folders;
        var layout = new StackPanel { Spacing = 10 };

        layout.Children.Add(new TextBlock
        {
            Text = "Steam, Epic and GOG are found on their own. These are the extra folders you " +
                   "asked us to look in.",
            TextWrapping = TextWrapping.Wrap,
            Opacity = 0.7,
            FontSize = 12,
        });

        var list = new StackPanel { Spacing = 6 };
        var toRemove = new List<string>();

        if (folders.All.Count == 0)
        {
            list.Children.Add(new TextBlock
            {
                Text = "None yet. Use “Add a folder…” for games installed outside a launcher.",
                Opacity = 0.5,
                FontSize = 12,
            });
        }

        foreach (var folder in folders.All)
        {
            var row = new Grid { ColumnDefinitions = new ColumnDefinitions("*,Auto") };

            var missing = folders.IsMissing(folder);
            var label = new TextBlock
            {
                Text = missing ? $"{folder}   (not found right now)" : folder,
                FontSize = 12,
                TextWrapping = TextWrapping.Wrap,
                VerticalAlignment = VerticalAlignment.Center,
                // A missing folder is flagged, never dropped on its own: an unplugged drive is
                // not a decision to forget what the user asked us to remember.
                Opacity = missing ? 0.55 : 1,
            };
            Grid.SetColumn(label, 0);

            var remove = new Button { Content = "Remove", FontSize = 11 };
            var captured = folder;
            remove.Click += (_, _) =>
            {
                toRemove.Add(captured);
                remove.IsEnabled = false;
                label.Opacity = 0.35;
                label.TextDecorations = TextDecorations.Strikethrough;
            };
            Grid.SetColumn(remove, 1);

            row.Children.Add(label);
            row.Children.Add(remove);
            list.Children.Add(row);
        }

        layout.Children.Add(list);

        if (!await ConfirmAsync("Folders you added", layout, "Apply")) return;
        if (toRemove.Count == 0) return;

        foreach (var folder in toRemove) folders.Remove(folder);
        await ScanAsync();
    }

    private void RefreshList()
    {
        var filter = SearchBox.Text ?? "";
        var previous = _selected?.Path;

        var items = _games
            .Where(g => filter.Length == 0 || g.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
            .Where(MatchesFilter)
            .Select(BuildListItem)
            .ToList();

        GameList.ItemsSource = items;

        if (previous is not null) SelectByPath(previous);
    }

    private bool MatchesFilter(GameInstall game)
    {
        if (_filter is null) return true;
        if (!_situations.TryGetValue(game.Path, out var situation)) return false;

        // "Already set up" covers everything installed, whatever else is true of it: someone
        // filtering on it wants their configured games, not a subset defined by a technicality.
        if (_filter == Situation.Ready)
        {
            return situation.Situation is Situation.Ready
                or Situation.UpdateAvailable
                or Situation.UnpublishedWork;
        }

        return situation.Situation == _filter;
    }

    /// <summary>
    /// A row states a situation and offers a verb, in the player's terms.
    ///
    /// The technical facts (runtime, Unity version, architecture) are not here on purpose: they
    /// answer "what is this" while someone scanning this list is asking "what can I do". They
    /// live in the card on the right, where they serve diagnosis.
    /// </summary>
    private ListBoxItem BuildListItem(GameInstall game)
    {
        var title = new TextBlock
        {
            Text = game.Name,
            FontWeight = FontWeight.SemiBold,
            TextTrimming = TextTrimming.CharacterEllipsis,
            Foreground = Brush("TextPrimary"),
        };

        var body = new StackPanel { Spacing = 3, Children = { title } };

        if (_situations.TryGetValue(game.Path, out var situation))
        {
            var headline = new TextBlock
            {
                Text = situation.Headline,
                FontSize = 11,
                TextWrapping = TextWrapping.Wrap,
                Foreground = situation.StatusKey is { } key ? Brush(key) : Brush("TextSecondary"),
            };
            body.Children.Add(headline);

            if (situation.Detail is { Length: > 0 } detail)
            {
                body.Children.Add(new TextBlock
                {
                    Text = detail,
                    FontSize = 10,
                    TextWrapping = TextWrapping.Wrap,
                    Foreground = Brush("TextMuted"),
                });
            }
        }

        return new ListBoxItem
        {
            Tag = game,
            Content = body,
        };
    }

    private void SelectByPath(string path)
    {
        if (GameList.ItemsSource is not IEnumerable<ListBoxItem> items) return;

        foreach (var item in items)
        {
            if (item.Tag is GameInstall game
                && string.Equals(game.Path, path, StringComparison.OrdinalIgnoreCase))
            {
                GameList.SelectedItem = item;
                return;
            }
        }
    }

    // ---------------------------------------------------------------- detail

    private async Task ShowSelectedAsync()
    {
        if (GameList.SelectedItem is not ListBoxItem { Tag: GameInstall game }) return;
        _selected = game;

        DetailPanel.Children.Clear();
        DetailPanel.Children.Add(new TextBlock { Text = game.Name, FontSize = 20, FontWeight = FontWeight.SemiBold });
        DetailPanel.Children.Add(new TextBlock { Text = "Reading...", Opacity = 0.6 });

        Busy(true, $"Reading {game.Name}...");
        var report = await _inventory.BuildReportAsync(game);
        Busy(false, "Ready.");

        // The user may have clicked elsewhere while we were reading.
        if (!ReferenceEquals(_selected, game)) return;

        RenderReport(report);
    }

    private void RenderReport(GameReport report)
    {
        var game = report.Game;
        DetailPanel.Children.Clear();

        DetailPanel.Children.Add(new TextBlock
        {
            Text = game.Name,
            FontSize = 20,
            FontWeight = FontWeight.SemiBold,
            Foreground = Brush("TextPrimary"),
            TextWrapping = TextWrapping.Wrap,
        });

        DetailPanel.Children.Add(new TextBlock
        {
            Text = game.Path,
            FontSize = 11,
            Foreground = Brush("TextMuted"),
            TextWrapping = TextWrapping.Wrap,
        });

        DetailPanel.Children.Add(Card(Facts(report)));

        foreach (var blocker in report.Blockers)
            DetailPanel.Children.Add(Callout(blocker, "CalloutErrorBg", "StatusError"));

        foreach (var warning in report.Warnings)
            DetailPanel.Children.Add(Callout(warning, "CalloutWarningBg", "StatusWarning"));

        DetailPanel.Children.Add(Card(Translations(report)));
        DetailPanel.Children.Add(Card(Actions(report)));
    }

    private static Control Facts(GameReport report)
    {
        var game = report.Game;
        var grid = new Grid { ColumnDefinitions = new ColumnDefinitions("150,*"), Margin = new Avalonia.Thickness(0, 6, 0, 0) };

        var rows = new List<(string Label, string Value)>
        {
            ("Type", game.Runtime switch
            {
                UnityRuntime.Mono => "Mono",
                UnityRuntime.Il2Cpp => "IL2CPP",
                _ => "could not be determined",
            }),
            ("Unity", game.UnityVersion ?? "unknown"),
            ("Mod loader", report.InstalledLoader is null
                ? "none installed"
                : $"{report.InstalledLoader.Display} {report.InstalledLoader.Version ?? ""}".Trim()),
            ("Plugin", report.InstalledPluginVersion ?? "not installed"),
        };

        if (report.RecommendationReason is not null)
            rows.Add(("What we would do", report.RecommendationReason));

        if (game.RunsUnderProton)
            rows.Add(("Proton", "yes — a Steam launch option is required"));

        for (var i = 0; i < rows.Count; i++)
        {
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Auto));

            var label = new TextBlock { Text = rows[i].Label, Foreground = Brush("TextMuted"), FontSize = 12, Margin = new Avalonia.Thickness(0, 3, 12, 3) };
            Grid.SetRow(label, i);
            Grid.SetColumn(label, 0);

            var value = new TextBlock { Text = rows[i].Value, TextWrapping = TextWrapping.Wrap, FontSize = 12, Foreground = Brush("TextSecondary"), Margin = new Avalonia.Thickness(0, 3, 0, 3) };
            Grid.SetRow(value, i);
            Grid.SetColumn(value, 1);

            grid.Children.Add(label);
            grid.Children.Add(value);
        }

        return grid;
    }

    private static Control Translations(GameReport report)
    {
        var panel = new StackPanel { Spacing = 6, Margin = new Avalonia.Thickness(0, 10, 0, 0) };
        panel.Children.Add(new TextBlock { Text = "Translations", FontWeight = FontWeight.SemiBold, Foreground = Brush("TextPrimary") });

        if (report.LocalTranslation is { } local)
        {
            var count = local.EntryCount < 0 ? "unreadable file" : $"{local.EntryCount} entries";
            var unsynced = local.LocalChanges > 0 ? $", {local.LocalChanges} not uploaded yet" : "";
            panel.Children.Add(new TextBlock { Text = $"On this machine: {count}{unsynced}", FontSize = 12, Foreground = Brush("TextSecondary") });
        }
        else
        {
            panel.Children.Add(new TextBlock { Text = "On this machine: none", FontSize = 12, Foreground = Brush("TextSecondary") });
        }

        if (report.MatchingOnline is { } mine)
        {
            panel.Children.Add(new TextBlock
            {
                Text = $"You already have this one: {mine}",
                FontSize = 12,
                TextWrapping = TextWrapping.Wrap,
                Foreground = Brush("StatusSuccess"),
            });
        }

        var alternatives = report.AlternativeOnline.ToList();
        if (alternatives.Count > 0)
        {
            panel.Children.Add(new TextBlock
            {
                Text = $"From the community ({alternatives.Count}):",
                FontSize = 12,
                Opacity = 0.8,
                Margin = new Avalonia.Thickness(0, 4, 0, 0),
            });

            foreach (var translation in alternatives.Take(8))
            {
                panel.Children.Add(new TextBlock
                {
                    Text = "• " + translation,
                    FontSize = 12,
                    Opacity = 0.75,
                    TextWrapping = TextWrapping.Wrap,
                    Margin = new Avalonia.Thickness(8, 0, 0, 0),
                });
            }

            // Never truncate silently.
            if (alternatives.Count > 8)
            {
                panel.Children.Add(new TextBlock
                {
                    Text = $"…and {alternatives.Count - 8} more on the website",
                    FontSize = 11,
                    Opacity = 0.5,
                    Margin = new Avalonia.Thickness(8, 0, 0, 0),
                });
            }
        }
        else if (report.OnlineSearchError is not null)
        {
            panel.Children.Add(new TextBlock
            {
                Text = $"Could not reach the community site ({report.OnlineSearchError}). " +
                       "A firewall blocking this tool looks exactly like this.",
                FontSize = 12,
                Opacity = 0.7,
                TextWrapping = TextWrapping.Wrap,
            });
        }
        else if (report.Game.SteamAppId is null)
        {
            panel.Children.Add(new TextBlock
            {
                Text = "This game was not found through Steam, so we cannot look it up automatically.",
                FontSize = 12,
                Opacity = 0.6,
                TextWrapping = TextWrapping.Wrap,
            });
        }

        return panel;
    }

    private Control Actions(GameReport report)
    {
        var panel = new StackPanel { Spacing = 10, Margin = new Avalonia.Thickness(0, 16, 0, 0) };
        var engine = new InstallEngine(_platform, _catalog);

        // The recommendation is a default, not a decision made for the user: some games work
        // with one loader and not another for reasons no probe can see.
        ComboBox? loaderPicker = null;

        if (report.InstalledLoader is not null)
        {
            panel.Children.Add(new TextBlock
            {
                Text = $"Using the {report.InstalledLoader.Display} already installed. " +
                       "It will not be replaced — other mods may depend on it.",
                FontSize = 12,
                Opacity = 0.65,
                TextWrapping = TextWrapping.Wrap,
            });
        }
        else if (report.EligibleLoaders.Count > 0)
        {
            loaderPicker = new ComboBox { Width = 260 };
            foreach (var loader in report.EligibleLoaders)
            {
                loaderPicker.Items.Add(new ComboBoxItem
                {
                    Content = loader == report.RecommendedLoader
                        ? $"{loader.Display} {loader.Version}  (recommended)"
                        : $"{loader.Display} {loader.Version}",
                    Tag = loader,
                });
            }
            loaderPicker.SelectedIndex = Math.Max(0,
                report.EligibleLoaders.ToList().IndexOf(report.RecommendedLoader!));

            var row = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 10 };
            row.Children.Add(new TextBlock
            {
                Text = "Mod loader",
                VerticalAlignment = VerticalAlignment.Center,
                Opacity = 0.55,
                FontSize = 12,
            });
            row.Children.Add(loaderPicker);
            panel.Children.Add(row);
        }

        var buttons = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8 };

        LoaderDescriptor? Chosen() =>
            (loaderPicker?.SelectedItem as ComboBoxItem)?.Tag as LoaderDescriptor;

        var plan = engine.Plan(report, ReleaseChannel.Stable, Chosen());
        var installed = report.InstalledPluginVersion is not null;

        var primary = new Button
        {
            Content = installed ? "Reinstall / update" : "Install",
            IsEnabled = plan is not null,
            Classes = { "primary" },
        };
        primary.Click += async (_, _) =>
            await RunInstallAsync(report, engine, engine.Plan(report, ReleaseChannel.Stable, Chosen()));
        buttons.Children.Add(primary);

        var uninstall = new Button
        {
            Content = "Uninstall...",
            IsEnabled = ReceiptStore.Read(report.Game.Path) is not null,
        };
        uninstall.Click += async (_, _) => await RunUninstallAsync(report);
        buttons.Children.Add(uninstall);

        panel.Children.Add(buttons);

        if (plan is null && report.Blockers.Count == 0)
        {
            panel.Children.Add(new TextBlock
            {
                Text = report.RecommendationReason ?? "Nothing can be installed here.",
                FontSize = 12,
                Opacity = 0.6,
                TextWrapping = TextWrapping.Wrap,
            });
        }

        return panel;
    }

    // ---------------------------------------------------------------- actions

    private async Task RunInstallAsync(GameReport report, InstallEngine engine, InstallPlan? plan)
    {
        if (plan is null) return;

        // Nothing is written before this is shown and accepted. The notes are recomputed for the
        // loader actually chosen, which may not be the recommended one shown in the report.
        var lines = plan.Describe().Select(line => "• " + line).ToList();

        var notes = _inventory.WarningsFor(plan.Loader, report.Game, plan.InstallLoader).ToList();
        if (notes.Count > 0)
        {
            lines.Add("");
            lines.AddRange(notes.Select(note => "! " + note));
        }

        var body = string.Join(Environment.NewLine, lines);
        if (!await ConfirmAsync($"Install into {report.Game.Name}?", body, "Install")) return;

        Busy(true, "Starting...");
        engine.Status += OnEngineStatus;

        var outcome = await engine.ApplyAsync(plan);

        engine.Status -= OnEngineStatus;
        Busy(false, outcome.Success ? "Done." : "Failed.");

        await MessageAsync(outcome.Success ? "Installed" : "Nothing was changed", outcome.Message);
        await ShowSelectedAsync();
    }

    private async Task RunUninstallAsync(GameReport report)
    {
        var engine = new UninstallEngine(_platform, _catalog);
        var available = engine.Available(report.Game);

        var loaderBox = new CheckBox
        {
            Content = "Also remove the mod loader",
            IsEnabled = available.RemoveLoader,
            IsChecked = false,
        };

        if (!available.RemoveLoader)
        {
            ToolTip.SetTip(loaderBox,
                "It was already there before, or other mods still use it.");
        }

        // Off by default, and deliberately worded so nobody deletes months of work by reflex.
        var dataBox = new CheckBox
        {
            Content = "Also remove my settings and translations (a copy is kept aside)",
            IsChecked = false,
        };

        var content = new StackPanel { Spacing = 10 };
        content.Children.Add(new TextBlock
        {
            Text = "The plugin will be removed. Files you changed since installing are left alone.",
            TextWrapping = TextWrapping.Wrap,
        });
        content.Children.Add(loaderBox);
        content.Children.Add(dataBox);

        if (!await ConfirmAsync($"Uninstall from {report.Game.Name}?", content, "Uninstall")) return;

        Busy(true, "Removing...");
        var outcome = engine.Apply(report.Game, new UninstallChoice(
            RemovePlugin: true,
            RemoveLoader: loaderBox.IsChecked == true,
            RemoveUserData: dataBox.IsChecked == true));
        Busy(false, "Ready.");

        var message = outcome.Message;
        if (outcome.Kept.Count > 0)
            message += Environment.NewLine + Environment.NewLine + "Left in place:" +
                       Environment.NewLine + string.Join(Environment.NewLine, outcome.Kept.Select(k => "• " + k));
        if (outcome.BackupPath is not null)
            message += Environment.NewLine + Environment.NewLine +
                       "Your settings and translations were copied to:" + Environment.NewLine + outcome.BackupPath;

        await MessageAsync("Uninstalled", message);
        await ShowSelectedAsync();
    }

    private void OnEngineStatus(string message) =>
        Dispatcher.UIThread.Post(() => Status(message));

    // ---------------------------------------------------------------- chrome

    private void Busy(bool busy, string message)
    {
        BusyBar.IsVisible = busy;
        Status(message);
    }

    private void Status(string message) => StatusText.Text = message;

    private Task<bool> ConfirmAsync(string title, string body, string confirmLabel) =>
        ConfirmAsync(title, new TextBlock { Text = body, TextWrapping = TextWrapping.Wrap }, confirmLabel);

    /// <summary>
    /// A modal confirmation. Written by hand rather than pulled from a dialog package: one
    /// window type is not worth a dependency that would also have to be kept current.
    /// </summary>
    private async Task<bool> ConfirmAsync(string title, Control body, string confirmLabel)
    {
        var result = false;

        var confirm = new Button { Content = confirmLabel, IsDefault = true };
        var cancel = new Button { Content = "Cancel", IsCancel = true };

        var buttons = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            Spacing = 8,
            HorizontalAlignment = HorizontalAlignment.Right,
            Children = { cancel, confirm },
        };

        var layout = new StackPanel { Spacing = 16, Margin = new Avalonia.Thickness(20) };
        layout.Children.Add(body);
        layout.Children.Add(buttons);

        var dialog = new Window
        {
            Title = title,
            Width = 520,
            SizeToContent = SizeToContent.Height,
            CanResize = false,
            WindowStartupLocation = WindowStartupLocation.CenterOwner,
            Content = new ScrollViewer { Content = layout },
        };

        confirm.Click += (_, _) => { result = true; dialog.Close(); };
        cancel.Click += (_, _) => dialog.Close();

        await dialog.ShowDialog(this);
        return result;
    }

    private async Task MessageAsync(string title, string body)
    {
        var ok = new Button { Content = "Close", IsDefault = true, HorizontalAlignment = HorizontalAlignment.Right };

        var layout = new StackPanel { Spacing = 16, Margin = new Avalonia.Thickness(20) };
        layout.Children.Add(new TextBlock { Text = body, TextWrapping = TextWrapping.Wrap });
        layout.Children.Add(ok);

        var dialog = new Window
        {
            Title = title,
            Width = 520,
            SizeToContent = SizeToContent.Height,
            CanResize = false,
            WindowStartupLocation = WindowStartupLocation.CenterOwner,
            Content = new ScrollViewer { Content = layout },
        };

        ok.Click += (_, _) => dialog.Close();
        await dialog.ShowDialog(this);
    }

    /// <summary>
    /// The site's card, reproduced: gray-800 fill, gray-700 edge, 8px radius, generous padding.
    /// Framing each section is what turns a wall of lines into things you can look at one at a
    /// time — which is the whole reason the site uses them.
    /// </summary>
    private static Control Card(Control content) => new Border
    {
        Background = Brush("SurfaceCard"),
        BorderBrush = Brush("BorderSubtle"),
        BorderThickness = new Avalonia.Thickness(1),
        CornerRadius = new Avalonia.CornerRadius(8),
        Padding = new Avalonia.Thickness(18, 15),
        Child = content,
    };

    /// <summary>Looks a brush up in the shared palette (Theme.axaml).</summary>
    private static IBrush? Brush(string key) =>
        Application.Current?.FindResource(key) as IBrush;

    /// <summary>
    /// A message that needs to stand out, tinted rather than shouted: the hue laid over the base
    /// surface, with a coloured edge. A flat saturated block would fight the rest of the window.
    /// </summary>
    private static Control Callout(string text, string backgroundKey, string edgeKey) => new Border
    {
        Background = Brush(backgroundKey),
        BorderBrush = Brush(edgeKey),
        BorderThickness = new Avalonia.Thickness(3, 0, 0, 0),
        CornerRadius = new Avalonia.CornerRadius(4),
        Padding = new Avalonia.Thickness(12, 9),
        Child = new TextBlock
        {
            Text = text,
            TextWrapping = TextWrapping.Wrap,
            FontSize = 12,
            Foreground = Brush("TextPrimary"),
        },
    };
}
