using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using UnityGameTranslator.Installer.Core.Api;
using UnityGameTranslator.Installer.Core.Catalog;
using UnityGameTranslator.Installer.Core.Detection;
using UnityGameTranslator.Installer.Core.Install;
using UnityGameTranslator.Installer.Core.Model;
using UnityGameTranslator.Installer.Core.Platform;

namespace UnityGameTranslator.Installer.Gui;

/// <summary>
/// The window. It renders what Core decided and calls back into Core — it holds no rule of its
/// own, which is why the command line and this show the same thing.
/// </summary>
public partial class MainWindow : Window
{
    private readonly IPlatform _platform;
    private LoaderCatalogDocument _catalog = null!;
    private GameInventory _inventory = null!;

    private readonly List<GameInstall> _games = new();
    private GameInstall? _selected;

    public MainWindow()
    {
        // InitializeComponent is generated by the Avalonia XAML compiler, and it is what wires
        // up the x:Name fields. Declaring one by hand hides it, leaving every named control
        // null — which fails at construction, not at build.
        InitializeComponent();

        _platform = PlatformFactory.Create();

        SearchBox.TextChanged += (_, _) => RefreshList();
        RescanButton.Click += async (_, _) => await ScanAsync();
        AddFolderButton.Click += async (_, _) => await AddFolderAsync();
        GameList.SelectionChanged += async (_, _) => await ShowSelectedAsync();

        Loaded += async (_, _) => await ScanAsync();
    }

    // ---------------------------------------------------------------- scanning

    private async Task ScanAsync()
    {
        Busy(true, "Looking for the loader catalog...");

        var result = await Task.Run(() => new CatalogProvider(_platform).Get());
        _catalog = result.Document;
        _inventory = new GameInventory(_platform, _catalog, new CatalogApiClient());

        Status($"Catalog: {_catalog.Loaders.Count} loaders ({result.Source}). Scanning your drives...");

        var found = await Task.Run(() => _inventory.ScanAll());

        _games.Clear();
        _games.AddRange(found.OrderBy(g => g.Name, StringComparer.OrdinalIgnoreCase));

        var blocked = _games.Count(g => !g.IsModdable);
        SubtitleText.Text = blocked == 0
            ? $"{_games.Count} Unity games found"
            : $"{_games.Count} Unity games found, {blocked} that cannot be modded";

        RefreshList();
        Busy(false, "Ready.");
    }

    private async Task AddFolderAsync()
    {
        var folders = await StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions
        {
            Title = "Where is the game installed?",
            AllowMultiple = false,
        });

        var path = folders.FirstOrDefault()?.TryGetLocalPath();
        if (path is null) return;

        var game = _inventory.ScanFolder(path);
        if (game is null)
        {
            Status("That folder does not hold a Unity game.");
            return;
        }

        // Adding a game we already know would leave two rows pointing at the same folder.
        if (_games.Any(g => string.Equals(g.Path, game.Path, StringComparison.OrdinalIgnoreCase)))
        {
            Status($"{game.Name} was already in the list.");
        }
        else
        {
            _games.Add(game);
            _games.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));
        }

        RefreshList();
        SelectByPath(game.Path);
    }

    private void RefreshList()
    {
        var filter = SearchBox.Text ?? "";
        var previous = _selected?.Path;

        var items = _games
            .Where(g => filter.Length == 0 || g.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
            .Select(BuildListItem)
            .ToList();

        GameList.ItemsSource = items;

        if (previous is not null) SelectByPath(previous);
    }

    private static ListBoxItem BuildListItem(GameInstall game)
    {
        var title = new TextBlock
        {
            Text = game.Name,
            FontWeight = FontWeight.SemiBold,
            TextTrimming = TextTrimming.CharacterEllipsis,
        };

        var runtime = game.Runtime switch
        {
            UnityRuntime.Mono => "Mono",
            UnityRuntime.Il2Cpp => "IL2CPP",
            _ => "unknown type",
        };

        var detail = new TextBlock
        {
            Text = game.IsModdable
                ? $"{runtime} · Unity {game.UnityVersion ?? "?"}"
                : $"cannot be modded — {game.VerdictDetail ?? game.Verdict.ToString()}",
            FontSize = 11,
            Opacity = game.IsModdable ? 0.6 : 0.85,
            Foreground = game.IsModdable ? null : new SolidColorBrush(Color.Parse("#E0A030")),
        };

        return new ListBoxItem
        {
            Tag = game,
            Padding = new Avalonia.Thickness(12, 8),
            Content = new StackPanel { Spacing = 2, Children = { title, detail } },
        };
    }

    private void SelectByPath(string path)
    {
        if (GameList.ItemsSource is not IEnumerable<ListBoxItem> items) return;

        foreach (var item in items)
        {
            if (item.Tag is GameInstall game
                && string.Equals(game.Path, path, StringComparison.OrdinalIgnoreCase))
            {
                GameList.SelectedItem = item;
                return;
            }
        }
    }

    // ---------------------------------------------------------------- detail

    private async Task ShowSelectedAsync()
    {
        if (GameList.SelectedItem is not ListBoxItem { Tag: GameInstall game }) return;
        _selected = game;

        DetailPanel.Children.Clear();
        DetailPanel.Children.Add(new TextBlock { Text = game.Name, FontSize = 20, FontWeight = FontWeight.SemiBold });
        DetailPanel.Children.Add(new TextBlock { Text = "Reading...", Opacity = 0.6 });

        Busy(true, $"Reading {game.Name}...");
        var report = await _inventory.BuildReportAsync(game);
        Busy(false, "Ready.");

        // The user may have clicked elsewhere while we were reading.
        if (!ReferenceEquals(_selected, game)) return;

        RenderReport(report);
    }

    private void RenderReport(GameReport report)
    {
        var game = report.Game;
        DetailPanel.Children.Clear();

        DetailPanel.Children.Add(new TextBlock
        {
            Text = game.Name,
            FontSize = 20,
            FontWeight = FontWeight.SemiBold,
            TextWrapping = TextWrapping.Wrap,
        });

        DetailPanel.Children.Add(new TextBlock
        {
            Text = game.Path,
            FontSize = 11,
            Opacity = 0.5,
            TextWrapping = TextWrapping.Wrap,
        });

        DetailPanel.Children.Add(Facts(report));

        foreach (var blocker in report.Blockers)
            DetailPanel.Children.Add(Callout(blocker, "#7A2E2E"));

        foreach (var warning in report.Warnings)
            DetailPanel.Children.Add(Callout(warning, "#5A4A20"));

        DetailPanel.Children.Add(Translations(report));
        DetailPanel.Children.Add(Actions(report));
    }

    private static Control Facts(GameReport report)
    {
        var game = report.Game;
        var grid = new Grid { ColumnDefinitions = new ColumnDefinitions("150,*"), Margin = new Avalonia.Thickness(0, 6, 0, 0) };

        var rows = new List<(string Label, string Value)>
        {
            ("Type", game.Runtime switch
            {
                UnityRuntime.Mono => "Mono",
                UnityRuntime.Il2Cpp => "IL2CPP",
                _ => "could not be determined",
            }),
            ("Unity", game.UnityVersion ?? "unknown"),
            ("Mod loader", report.InstalledLoader is null
                ? "none installed"
                : $"{report.InstalledLoader.Display} {report.InstalledLoader.Version ?? ""}".Trim()),
            ("Plugin", report.InstalledPluginVersion ?? "not installed"),
        };

        if (report.RecommendationReason is not null)
            rows.Add(("What we would do", report.RecommendationReason));

        if (game.RunsUnderProton)
            rows.Add(("Proton", "yes — a Steam launch option is required"));

        for (var i = 0; i < rows.Count; i++)
        {
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Auto));

            var label = new TextBlock { Text = rows[i].Label, Opacity = 0.55, FontSize = 12, Margin = new Avalonia.Thickness(0, 3, 12, 3) };
            Grid.SetRow(label, i);
            Grid.SetColumn(label, 0);

            var value = new TextBlock { Text = rows[i].Value, TextWrapping = TextWrapping.Wrap, FontSize = 12, Margin = new Avalonia.Thickness(0, 3, 0, 3) };
            Grid.SetRow(value, i);
            Grid.SetColumn(value, 1);

            grid.Children.Add(label);
            grid.Children.Add(value);
        }

        return grid;
    }

    private static Control Translations(GameReport report)
    {
        var panel = new StackPanel { Spacing = 6, Margin = new Avalonia.Thickness(0, 10, 0, 0) };
        panel.Children.Add(new TextBlock { Text = "Translations", FontWeight = FontWeight.SemiBold });

        if (report.LocalTranslation is { } local)
        {
            var count = local.EntryCount < 0 ? "unreadable file" : $"{local.EntryCount} entries";
            var unsynced = local.LocalChanges > 0 ? $", {local.LocalChanges} not uploaded yet" : "";
            panel.Children.Add(new TextBlock { Text = $"On this machine: {count}{unsynced}", FontSize = 12, Opacity = 0.8 });
        }
        else
        {
            panel.Children.Add(new TextBlock { Text = "On this machine: none", FontSize = 12, Opacity = 0.8 });
        }

        if (report.MatchingOnline is { } mine)
        {
            panel.Children.Add(new TextBlock
            {
                Text = $"You already have this one: {mine}",
                FontSize = 12,
                TextWrapping = TextWrapping.Wrap,
                Foreground = new SolidColorBrush(Color.Parse("#6FBF73")),
            });
        }

        var alternatives = report.AlternativeOnline.ToList();
        if (alternatives.Count > 0)
        {
            panel.Children.Add(new TextBlock
            {
                Text = $"From the community ({alternatives.Count}):",
                FontSize = 12,
                Opacity = 0.8,
                Margin = new Avalonia.Thickness(0, 4, 0, 0),
            });

            foreach (var translation in alternatives.Take(8))
            {
                panel.Children.Add(new TextBlock
                {
                    Text = "• " + translation,
                    FontSize = 12,
                    Opacity = 0.75,
                    TextWrapping = TextWrapping.Wrap,
                    Margin = new Avalonia.Thickness(8, 0, 0, 0),
                });
            }

            // Never truncate silently.
            if (alternatives.Count > 8)
            {
                panel.Children.Add(new TextBlock
                {
                    Text = $"…and {alternatives.Count - 8} more on the website",
                    FontSize = 11,
                    Opacity = 0.5,
                    Margin = new Avalonia.Thickness(8, 0, 0, 0),
                });
            }
        }
        else if (report.OnlineSearchError is not null)
        {
            panel.Children.Add(new TextBlock
            {
                Text = $"Could not reach the community site ({report.OnlineSearchError}). " +
                       "A firewall blocking this tool looks exactly like this.",
                FontSize = 12,
                Opacity = 0.7,
                TextWrapping = TextWrapping.Wrap,
            });
        }
        else if (report.Game.SteamAppId is null)
        {
            panel.Children.Add(new TextBlock
            {
                Text = "This game was not found through Steam, so we cannot look it up automatically.",
                FontSize = 12,
                Opacity = 0.6,
                TextWrapping = TextWrapping.Wrap,
            });
        }

        return panel;
    }

    private Control Actions(GameReport report)
    {
        var panel = new StackPanel { Spacing = 10, Margin = new Avalonia.Thickness(0, 16, 0, 0) };
        var buttons = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8 };

        var engine = new InstallEngine(_platform, _catalog);
        var plan = engine.Plan(report);

        var installed = report.InstalledPluginVersion is not null;

        var primary = new Button
        {
            Content = installed ? "Reinstall / update" : "Install",
            IsEnabled = plan is not null,
        };
        primary.Click += async (_, _) => await RunInstallAsync(report, engine, plan);
        buttons.Children.Add(primary);

        var uninstall = new Button
        {
            Content = "Uninstall...",
            IsEnabled = ReceiptStore.Read(report.Game.Path) is not null,
        };
        uninstall.Click += async (_, _) => await RunUninstallAsync(report);
        buttons.Children.Add(uninstall);

        panel.Children.Add(buttons);

        if (plan is null && report.Blockers.Count == 0)
        {
            panel.Children.Add(new TextBlock
            {
                Text = report.RecommendationReason ?? "Nothing can be installed here.",
                FontSize = 12,
                Opacity = 0.6,
                TextWrapping = TextWrapping.Wrap,
            });
        }

        return panel;
    }

    // ---------------------------------------------------------------- actions

    private async Task RunInstallAsync(GameReport report, InstallEngine engine, InstallPlan? plan)
    {
        if (plan is null) return;

        // Nothing is written before this is shown and accepted.
        var body = string.Join(Environment.NewLine, plan.Describe().Select(line => "• " + line));
        if (!await ConfirmAsync($"Install into {report.Game.Name}?", body, "Install")) return;

        Busy(true, "Starting...");
        engine.Status += OnEngineStatus;

        var outcome = await engine.ApplyAsync(plan);

        engine.Status -= OnEngineStatus;
        Busy(false, outcome.Success ? "Done." : "Failed.");

        await MessageAsync(outcome.Success ? "Installed" : "Nothing was changed", outcome.Message);
        await ShowSelectedAsync();
    }

    private async Task RunUninstallAsync(GameReport report)
    {
        var engine = new UninstallEngine(_platform, _catalog);
        var available = engine.Available(report.Game);

        var loaderBox = new CheckBox
        {
            Content = "Also remove the mod loader",
            IsEnabled = available.RemoveLoader,
            IsChecked = false,
        };

        if (!available.RemoveLoader)
        {
            ToolTip.SetTip(loaderBox,
                "It was already there before, or other mods still use it.");
        }

        // Off by default, and deliberately worded so nobody deletes months of work by reflex.
        var dataBox = new CheckBox
        {
            Content = "Also remove my settings and translations (a copy is kept aside)",
            IsChecked = false,
        };

        var content = new StackPanel { Spacing = 10 };
        content.Children.Add(new TextBlock
        {
            Text = "The plugin will be removed. Files you changed since installing are left alone.",
            TextWrapping = TextWrapping.Wrap,
        });
        content.Children.Add(loaderBox);
        content.Children.Add(dataBox);

        if (!await ConfirmAsync($"Uninstall from {report.Game.Name}?", content, "Uninstall")) return;

        Busy(true, "Removing...");
        var outcome = engine.Apply(report.Game, new UninstallChoice(
            RemovePlugin: true,
            RemoveLoader: loaderBox.IsChecked == true,
            RemoveUserData: dataBox.IsChecked == true));
        Busy(false, "Ready.");

        var message = outcome.Message;
        if (outcome.Kept.Count > 0)
            message += Environment.NewLine + Environment.NewLine + "Left in place:" +
                       Environment.NewLine + string.Join(Environment.NewLine, outcome.Kept.Select(k => "• " + k));
        if (outcome.BackupPath is not null)
            message += Environment.NewLine + Environment.NewLine +
                       "Your settings and translations were copied to:" + Environment.NewLine + outcome.BackupPath;

        await MessageAsync("Uninstalled", message);
        await ShowSelectedAsync();
    }

    private void OnEngineStatus(string message) =>
        Dispatcher.UIThread.Post(() => Status(message));

    // ---------------------------------------------------------------- chrome

    private void Busy(bool busy, string message)
    {
        BusyBar.IsVisible = busy;
        Status(message);
    }

    private void Status(string message) => StatusText.Text = message;

    private Task<bool> ConfirmAsync(string title, string body, string confirmLabel) =>
        ConfirmAsync(title, new TextBlock { Text = body, TextWrapping = TextWrapping.Wrap }, confirmLabel);

    /// <summary>
    /// A modal confirmation. Written by hand rather than pulled from a dialog package: one
    /// window type is not worth a dependency that would also have to be kept current.
    /// </summary>
    private async Task<bool> ConfirmAsync(string title, Control body, string confirmLabel)
    {
        var result = false;

        var confirm = new Button { Content = confirmLabel, IsDefault = true };
        var cancel = new Button { Content = "Cancel", IsCancel = true };

        var buttons = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            Spacing = 8,
            HorizontalAlignment = HorizontalAlignment.Right,
            Children = { cancel, confirm },
        };

        var layout = new StackPanel { Spacing = 16, Margin = new Avalonia.Thickness(20) };
        layout.Children.Add(body);
        layout.Children.Add(buttons);

        var dialog = new Window
        {
            Title = title,
            Width = 520,
            SizeToContent = SizeToContent.Height,
            CanResize = false,
            WindowStartupLocation = WindowStartupLocation.CenterOwner,
            Content = new ScrollViewer { Content = layout },
        };

        confirm.Click += (_, _) => { result = true; dialog.Close(); };
        cancel.Click += (_, _) => dialog.Close();

        await dialog.ShowDialog(this);
        return result;
    }

    private async Task MessageAsync(string title, string body)
    {
        var ok = new Button { Content = "Close", IsDefault = true, HorizontalAlignment = HorizontalAlignment.Right };

        var layout = new StackPanel { Spacing = 16, Margin = new Avalonia.Thickness(20) };
        layout.Children.Add(new TextBlock { Text = body, TextWrapping = TextWrapping.Wrap });
        layout.Children.Add(ok);

        var dialog = new Window
        {
            Title = title,
            Width = 520,
            SizeToContent = SizeToContent.Height,
            CanResize = false,
            WindowStartupLocation = WindowStartupLocation.CenterOwner,
            Content = new ScrollViewer { Content = layout },
        };

        ok.Click += (_, _) => dialog.Close();
        await dialog.ShowDialog(this);
    }

    private static Control Callout(string text, string background) => new Border
    {
        Background = new SolidColorBrush(Color.Parse(background)),
        CornerRadius = new Avalonia.CornerRadius(4),
        Padding = new Avalonia.Thickness(12, 9),
        Child = new TextBlock { Text = text, TextWrapping = TextWrapping.Wrap, FontSize = 12 },
    };
}
